get http://localhost:3005/info
###
get http://localhost:3005/api/persons
###
DELETE http://localhost:3005/api/persons/65a10363f3467fba4a855e89
###
get http://localhost:3005/api/persons/65a10363f3467fba4a855e89 
###
POST http://localhost:3005/api/persons
Content-Type: application/json

{
    "name": "Takam Christophe",
    "number": "237-86512397"
}
###
get https://phonebookserver-kngc.onrender.com/api/persons
###
DELETE https://phonebookserver-kngc.onrender.com/api/persons/4
###
POST https://phonebookserver-kngc.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Takam Christophe",
    "number": "237-86512397"
}
